---
title: "Midterm 2"
author: "Ishita Dutta, 918193342"
date: "2/28/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1a:
```{r}
pvec = c(1, 3, 5)
var2vec = c(12.021, 10.290,  4.44)
myAIC <- function(p, var2) {
  val1 = 90 * log(var2)
  val2 = 2 * p
  return(val1 + val2)
}
finalvec = vector()
for(i in 1:3) {
  print(myAIC(pvec[i], var2vec[i]))
}

```
_Solution:_ On the basis of the AIC criterion, the best model is the AR(2) model, as it has the smallest AIC value. 

# 1b:
```{r echo = FALSE}
x89 = 32.71
x90 = 30.59
```

```{r echo = FALSE}
xt <- function(p1, p2) {
  val1 = 0.6673 * p1
  val2 = -0.7480 * p2
  return(val1 + val2)
}
x91 = xt(x89, x90)
x92 = xt(x90, x91)
predicted = c(x91,x92)
predicted
```


# 2a:
```{r}
n = 90
Tn = (17.7/((1 + 0.5048)^2))
var.squared = Tn/n
var.squared
```

# 2b:
```{r}
lower =  54.956 - (1.96 * (var.squared ^ 0.5))
upper =  54.956 + (1.96 * (var.squared ^ 0.5))
lower
upper
```
Interval in between [54.37838, 55.53362].

# 2c:
```{r}
(-0.5048) / 0.0934
```
This value is much smaller than 1, so we can easily reject the Ho = 0 at level 0.01.

# 3b
















