---
title: "HW2 STA 137"
author: "Ishita Dutta"
date: "1/30/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Getting Data Setup
```{r}
library(readxl)
library(ggplot2)
#1a)
crude <- read_excel("USCrude1.xls", sheet = 2, skip = 2, col_names = TRUE)
Y = crude$`U.S. Field Production of Crude Oil (Thousand Barrels)`
tm = 1:119
model = loess(Y~tm,span=0.2)
model
ggplot(crude, aes(x = tm + 1900, y = Y)) + geom_point() + ggtitle("US Crude Oil Over Time") + xlab("Time") + ylab("Production(Thousand Barrels)") + geom_smooth(aes(group = 1), method="loess", formula=y~x, se = FALSE, col = "green") 
ggplot(crude, aes(x = tm + 1900, y = Y - model$fitted)) + geom_point() + ggtitle("Xt vs Time") + xlab("Time") + ylab("Xt") + geom_smooth(aes(group = 1), method="loess", formula=y~x, se = FALSE, col = "dark green") 
```

```{r}
#1b)
ylog = log(Y, base = exp(1))
ggplot(crude, aes(x = tm + 1900, y = log(Y, base = exp(1)))) + geom_point() + ggtitle("US Crude Oil Over Time") + xlab("Time") + ylab("Production(Thousand Barrels)") + geom_smooth(aes(group = 1), method="loess", formula=y~x, se = FALSE, col = "red")
ggplot(crude, aes(x = tm + 1900, y = ylog - model$fitted)) + geom_point() + ggtitle("Xt vs Time") + xlab("Time") + ylab("Xt") + geom_smooth(aes(group = 1), method="loess", formula=y~x, se = FALSE, col = "maroon") 
cat("working with Yt only as points in the residual plot are more around 0 as opposed to fitting what seems like a nonlinear line with the log(Yt)")
```


```{r}
#1c)
Xt = ylog - model$fitted
Xt2 = Y - model$fitted
ggplot(data=crude, aes(y = Xt)) + geom_histogram(bins = 26, color = "black", fill = "white") 
qqnorm(Xt2)
qqline(Xt2, col = "salmon")
```


```{r}
#1d)
acf(Xt, lag.max = 10)

```

```{r}
#1e)
cat("Ho --> autocorrelations = 0, Ha --> autocorrections != 0
    Decision Rule --> if p-value < 0.05, reject null")
Box.test(Xt, type = "Ljung-Box")
cat("As p-value < 2.2e-16 < 0.05, we reject the null hypothesis and conclude that the autocorrelation for this model is not 0.")
```


