---
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# P4:

```{r}
#reading the data from table 8.4 and assigning column names
tab=read.table("T1-10.dat")
head(tab)

#modifying the data as required
bulls=tab[3:9]
colnames(bulls)=c("YrHgt","FtFrBody","PrctFFB","Frame","BkFat","SaleHt","SaleWt")
head(bulls)
```

```{r}
#Principal Component Analysis
#Simple Statistics
means= colMeans(bulls)
SD= apply(bulls,2,sd)
stat= rbind(means,SD)
stat

#Calculating the covariance matrix,S
S=cov(bulls)
S

#Sample Principal components
e= eigen(S)
e_val= e$values
e_vec= e$vectors
difference= round(-1*diff(e_val),6)
prop_val= e_val/sum(e_val)
total= cumsum(prop_val)

e_value=data.frame(e_val, Difference= c(difference, ''), prop_val, total)
rownames(e_value)= c('PC1', 'PC2','PC3','PC4','PC5','PC6','PC7')
e_value

e_vector=as.data.frame(e_vec)
colnames(e_vector)=c("PC1","PC2","PC3","PC4","PC5","PC6","PC7")
rownames(e_vector)=c("YrHgt","FtFrBody","PrctFFB","Frame","BkFat","SaleHt","SaleWt")
e_vector
```

```{r}
bull_mat=as.matrix(bulls)
e_vector_mat=as.matrix(e_vector)
mult=bull_mat%*%e_vector_mat
plot(mult[,2],mult[,1],xlab="y2", ylab="y1")
```

```{r}
qqnorm(mult[,1],xlab="q1",ylab="y1")

```
